apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: threescaletenants.threescale.net
spec:
  group: threescale.net
  names:
    kind: ThreeScaleTenant
    listKind: ThreeScaleTenantList
    plural: threescaletenants
    singular: threescaletenant
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            tenant:
              type: object
              properties:
                id:
                  type: integer
                domain:
                  type: string
                admin_domain:
                  type: string
                state:
                  type: string
            name:
              type: string
            threeScaleName:
              type: string
            adminUsername:
              type: string
            adminEmail:
              type: string
            adminPassword:
              type: string
            adminCredentials:
              type: string
            users:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                  username:
                    type: string
                  password:
                    type: string
                  email:
                    type: string
                  role:
                    type: string
                  state:
                    type: string
            seedUsers:
              type: object
              properties:
                count:
                  type: integer
                nameFormat:
                  type: string
                emailFormat:
                  type: string
                password:
                  type: string
                role:
                  type: string
            authProviders:
              type: array
              items:
                type: object
                properties:
                  kind:
                    type: string
                  name:
                    type: string
                  client_id:
                    type: string
                  client_secret:
                    type: string
                  site:
                    type: string
                  skip_ssl_certificate_verification:
                    type: boolean
                  published:
                    type: boolean
