apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: threescales.threescale.net
spec:
  group: threescale.net
  names:
    kind: ThreeScale
    listKind: ThreeScaleList
    plural: threescales
    singular: threescale
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            adminUsername:
              type: string
              pattern: '^[a-z][a-z0-9]+$'
            adminEmail:
              type: string
            adminCredentials:
              type: string
            routeSuffix:
              type: string
            rwxStorageClass:
              type: string
            wildcardPolicy:
              type: string
            mysqlPvcSize:
              type: string
            users:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                  username:
                    type: string
                  password:
                    type: string
                  email:
                    type: string
                  role:
                    type: string
                  state:
                    type: string
            seedUsers:
              type: object
              properties:
                count:
                  type: integer
                nameFormat:
                  type: string
                emailFormat:
                  type: string
                password:
                  type: string
                role:
                  type: string
            authProviders:
              type: array
              items:
                type: object
                properties:
                  kind:
                    type: string
                  name:
                    type: string
                  client_id:
                    type: string
                  client_secret:
                    type: string
                  site:
                    type: string
                  skip_ssl_certificate_verification:
                    type: boolean
                  published:
                    type: boolean

