apiVersion: threescale.net/v1alpha1
kind: ThreeScale
metadata:
  name: example-threescale
spec:
  tenantName: 3scale
  #The route suffix
  routeSuffix: apps.mnairn-75c1.openshiftworkshop.com
  #Storage class for RWX system PVC
  rwxStorageClass: ""
  wildcardPolicy: Subdomain
  mysqlPvcSize: 100Gi
  #Admin Username
  adminUsername: admin@example.com
  #Admin Email
  adminEmail: admin@example.com
