// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeedUsersConfig) DeepCopyInto(out *SeedUsersConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeedUsersConfig.
func (in *SeedUsersConfig) DeepCopy() *SeedUsersConfig {
	if in == nil {
		return nil
	}
	out := new(SeedUsersConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThreeScale) DeepCopyInto(out *ThreeScale) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThreeScale.
func (in *ThreeScale) DeepCopy() *ThreeScale {
	if in == nil {
		return nil
	}
	out := new(ThreeScale)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThreeScale) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThreeScaleApiAuthProvider) DeepCopyInto(out *ThreeScaleApiAuthProvider) {
	*out = *in
	if in.AuthProvider != nil {
		in, out := &in.AuthProvider, &out.AuthProvider
		*out = new(ThreeScaleAuthProvider)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThreeScaleApiAuthProvider.
func (in *ThreeScaleApiAuthProvider) DeepCopy() *ThreeScaleApiAuthProvider {
	if in == nil {
		return nil
	}
	out := new(ThreeScaleApiAuthProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThreeScaleApiUser) DeepCopyInto(out *ThreeScaleApiUser) {
	*out = *in
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(ThreeScaleUser)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThreeScaleApiUser.
func (in *ThreeScaleApiUser) DeepCopy() *ThreeScaleApiUser {
	if in == nil {
		return nil
	}
	out := new(ThreeScaleApiUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThreeScaleAuthProvider) DeepCopyInto(out *ThreeScaleAuthProvider) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThreeScaleAuthProvider.
func (in *ThreeScaleAuthProvider) DeepCopy() *ThreeScaleAuthProvider {
	if in == nil {
		return nil
	}
	out := new(ThreeScaleAuthProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThreeScaleAuthProviderList) DeepCopyInto(out *ThreeScaleAuthProviderList) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]*ThreeScaleApiAuthProvider, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ThreeScaleApiAuthProvider)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThreeScaleAuthProviderList.
func (in *ThreeScaleAuthProviderList) DeepCopy() *ThreeScaleAuthProviderList {
	if in == nil {
		return nil
	}
	out := new(ThreeScaleAuthProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThreeScaleAuthProviderPair) DeepCopyInto(out *ThreeScaleAuthProviderPair) {
	*out = *in
	if in.TsAuthProvider != nil {
		in, out := &in.TsAuthProvider, &out.TsAuthProvider
		*out = new(ThreeScaleAuthProvider)
		**out = **in
	}
	if in.SpecAuthProvider != nil {
		in, out := &in.SpecAuthProvider, &out.SpecAuthProvider
		*out = new(ThreeScaleAuthProvider)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThreeScaleAuthProviderPair.
func (in *ThreeScaleAuthProviderPair) DeepCopy() *ThreeScaleAuthProviderPair {
	if in == nil {
		return nil
	}
	out := new(ThreeScaleAuthProviderPair)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThreeScaleList) DeepCopyInto(out *ThreeScaleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ThreeScale, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThreeScaleList.
func (in *ThreeScaleList) DeepCopy() *ThreeScaleList {
	if in == nil {
		return nil
	}
	out := new(ThreeScaleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThreeScaleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThreeScaleSpec) DeepCopyInto(out *ThreeScaleSpec) {
	*out = *in
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]ThreeScaleUser, len(*in))
		copy(*out, *in)
	}
	out.SeedUsers = in.SeedUsers
	if in.AuthProviders != nil {
		in, out := &in.AuthProviders, &out.AuthProviders
		*out = make([]ThreeScaleAuthProvider, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThreeScaleSpec.
func (in *ThreeScaleSpec) DeepCopy() *ThreeScaleSpec {
	if in == nil {
		return nil
	}
	out := new(ThreeScaleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThreeScaleStatus) DeepCopyInto(out *ThreeScaleStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThreeScaleStatus.
func (in *ThreeScaleStatus) DeepCopy() *ThreeScaleStatus {
	if in == nil {
		return nil
	}
	out := new(ThreeScaleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThreeScaleTenant) DeepCopyInto(out *ThreeScaleTenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThreeScaleTenant.
func (in *ThreeScaleTenant) DeepCopy() *ThreeScaleTenant {
	if in == nil {
		return nil
	}
	out := new(ThreeScaleTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThreeScaleTenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThreeScaleTenantList) DeepCopyInto(out *ThreeScaleTenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ThreeScaleTenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThreeScaleTenantList.
func (in *ThreeScaleTenantList) DeepCopy() *ThreeScaleTenantList {
	if in == nil {
		return nil
	}
	out := new(ThreeScaleTenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThreeScaleTenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThreeScaleTenantSpec) DeepCopyInto(out *ThreeScaleTenantSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThreeScaleTenantSpec.
func (in *ThreeScaleTenantSpec) DeepCopy() *ThreeScaleTenantSpec {
	if in == nil {
		return nil
	}
	out := new(ThreeScaleTenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThreeScaleTenantStatus) DeepCopyInto(out *ThreeScaleTenantStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThreeScaleTenantStatus.
func (in *ThreeScaleTenantStatus) DeepCopy() *ThreeScaleTenantStatus {
	if in == nil {
		return nil
	}
	out := new(ThreeScaleTenantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThreeScaleUser) DeepCopyInto(out *ThreeScaleUser) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThreeScaleUser.
func (in *ThreeScaleUser) DeepCopy() *ThreeScaleUser {
	if in == nil {
		return nil
	}
	out := new(ThreeScaleUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThreeScaleUserList) DeepCopyInto(out *ThreeScaleUserList) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]*ThreeScaleApiUser, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ThreeScaleApiUser)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThreeScaleUserList.
func (in *ThreeScaleUserList) DeepCopy() *ThreeScaleUserList {
	if in == nil {
		return nil
	}
	out := new(ThreeScaleUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThreeScaleUserPair) DeepCopyInto(out *ThreeScaleUserPair) {
	*out = *in
	if in.TsUser != nil {
		in, out := &in.TsUser, &out.TsUser
		*out = new(ThreeScaleUser)
		**out = **in
	}
	if in.SpecUser != nil {
		in, out := &in.SpecUser, &out.SpecUser
		*out = new(ThreeScaleUser)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThreeScaleUserPair.
func (in *ThreeScaleUserPair) DeepCopy() *ThreeScaleUserPair {
	if in == nil {
		return nil
	}
	out := new(ThreeScaleUserPair)
	in.DeepCopyInto(out)
	return out
}
